import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class AttendancePDFService {
  
  // 'attendanceList' मध्ये तुझ्या स्क्रीनवरचा डेटा पाठवायचा
  static Future<void> downloadPresentData(String department, String date, List<Map<String, dynamic>> attendanceList) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              // Header
              pw.Text("$department Department", style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold, color: PdfColors.blue900)),
              pw.Text("Attendance Report", style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 5),
              pw.Text("Date: $date", style: pw.TextStyle(fontSize: 12, color: PdfColors.grey700)),
              pw.Divider(thickness: 1.5),
              pw.SizedBox(height: 20),

              // Table
              pw.TableHelper.fromTextArray(
                headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white),
                headerDecoration: pw.BoxDecoration(color: PdfColors.blue900),
                cellHeight: 25,
                cellAlignments: {
                  0: pw.Alignment.centerLeft,
                  1: pw.Alignment.centerLeft,
                  2: pw.Alignment.center,
                  3: pw.Alignment.center,
                },
                headers: <String>['Roll No', 'Student Name', 'Status', 'Time'],
                data: attendanceList.map((item) {
                  return [
                    item['rollNo']?.toString() ?? '-',
                    item['studentName']?.toString() ?? '-',
                    item['status']?.toString() ?? 'Present',
                    item['time']?.toString() ?? '-',
                  ];
                }).toList(),
              ),
              
              pw.Spacer(),
              pw.Align(
                alignment: pw.Alignment.centerRight,
                child: pw.Text("Generated by Smart Attendance App", style: pw.TextStyle(fontSize: 9, color: PdfColors.grey)),
              ),
            ],
          );
        },
      ),
    );

    // थेट डाउनलोड/शेअर डायलॉग उघडेल
    await Printing.layoutPdf(
      onLayout: (format) async => pdf.save(),
      name: '${department}_Attendance_$date.pdf',
    );
  }
}